# Clase 7: Funciones, módulos y objetos

In [1]:
import numpy as np

Ya hemos visto varios ejemplos de funciones como:

In [3]:
np.sin(3)

0.1411200080598672

In [4]:
np.random.rand(19)

array([0.35376037, 0.56582445, 0.06124196, 0.66966934, 0.7939277 ,
       0.52945601, 0.19650891, 0.2500534 , 0.60758599, 0.99698132,
       0.11985673, 0.46420303, 0.70674195, 0.67843778, 0.78264174,
       0.46821447, 0.47720854, 0.24055075, 0.47035311])

In [6]:
type(17.32)

float

In [7]:
np.log(np.sin(3))

-1.958144629610086

## Crear nuevas funciones

In [8]:
def ejemplo():               # Encabezado
    print('Mi ejemplo.')     # Cuerpo

In [9]:
ejemplo()

Mi ejemplo.


In [10]:
# Ahora le pasamos un argumento a la función.

def impresora(algo):
    print(algo)
    print(algo)

In [11]:
impresora('Me repito')

Me repito
Me repito


In [12]:
impresora(np.array([1,2,2]))

[1 2 2]
[1 2 2]


In [13]:
x = 10
impresora(x)

10
10


In [17]:
# Los parámetros y las variables viven sólo dentro de la función

def aumentar(x):
    y = 1
    x = x + y
    print(x)

In [18]:
x = 10
aumentar(x)

11


In [19]:
x

10

In [20]:
y

NameError: name 'y' is not defined

In [21]:
x = 1
aumentar(11)

12


In [22]:
x

1

Las funciones sirven principalmente para lo siguiente:

* Ayuda a organizar un código en partes lógicas. Uno puede diseñar el código atacando un problema a la vez.
* Muchas veces uno tiene que escribir el mismo código muchas veces. En esos casos tiene sentido escribir una función y usarla, en vez de repetir el mismo código. Si hay un error en el código, es más fácil corregirlo una sola vez en la función.
* Las funciones bien escritas se pueden reutilizar en varios códigos.
* Sirven como funciones matemáticas.

## Funciones que retornan un valor

In [23]:
def area(lado):
    a = lado*lado
    return a

In [24]:
area(2)

4

In [25]:
x = area(2)

In [26]:
x

4

In [27]:
x = aumentar(2)

3


In [28]:
x

In [29]:
def valor_absoluto(x):
    if x >= 0:
        return x
    elif x < 0:
        return -x

In [30]:
valor_absoluto(-1)

1

In [31]:
def valor_absoluto(x):
    if x > 0:
        return x
    elif x < 0:
        return -x

In [32]:
valor_absoluto(0)

In [33]:
def divisible(x, y):
    '''Esta función regresa True si x es divisible por y,
    de otro modo regresa False'''
    
    if (x%y == 0):
        return True
    else:
        return False
    
x = 120
y = 10
if divisible(x,y):
    print(x, 'es divisible por', y)

120 es divisible por 10


In [34]:
def divisible(x, y):
    '''Esta función regresa True si x es divisible por y,
    de otro modo regresa False'''
    
    return x%y == 0

## Objetos

Los objetos empaquetan funciones y datos. La idea es que el objeto puede tener propiedades y puede realizar acciones. Para ejecuttar una acción sobre un objeto se usa la notación punto. Ya hemos visto varios ejemplos:

In [38]:
mi_arreglo = np.zeros((10,2))

In [40]:
mi_arreglo

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
mi_arreglo.transpose()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Algo que puede ser confuso es que algunas acciones modifican el objeto y otras no.

In [42]:
mi_arreglo

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

No vamos a profundizar mucho en cómo crear objetos, sólo lo básico.

In [48]:
class mi_objeto():
    
    def __init__(self, x):
        self.datos = x
    
    def cambiar_dato(self, y):
        self.datos = y
        
    def imprimir_dato(self):
        print(self.datos)

In [49]:
obj = mi_objeto(2)

In [50]:
obj.imprimir_dato()

2


In [51]:
obj.cambiar_dato(5)

In [52]:
obj.imprimir_dato()

5


## Módulos

Hemos importado ya varios módulos a lo largo del curso. Para crear un módulo propio hay que escribir un código python autocontenido en un archivo con extensión .py. Luego se puede importar si está en el mismo directorio que el código que uno quiere ejecutar.

In [1]:
import ejemplo

In [3]:
ejemplo.ejemplo1()

Una función


In [4]:
ejemplo.ejemplo2()

Otra cosa


1

In [5]:
from ejemplo import ejemplo1

In [6]:
ejemplo1()

Una función


In [7]:
from ejemplo import ejemplo2 as ej2

In [8]:
ej2()

Otra cosa


1

In [9]:
import ejemplo as ej

In [11]:
ej.ejemplo2()

Otra cosa


1

## Tomar el tiempo que tarda una operación

Tomado del libro "Introducing Python" de Bill Lubanovic, O'Reilly, 2014

Es útil medir el tiempo que tarda un cálculo, por ejemplo para comparar algoritmos diferentes o librerías distintas.

In [1]:
from time import time

In [2]:
t1 = time()
[[i*j for i in range(1000)] for j in range(1000)]
print(time() - t1)

0.0936729907989502


In [7]:
from timeit import timeit

def lista1():
    resultado = []
    for valor in range(1000):
        resultado.append(valor)
    return resultado

def lista2():
    resultado = [valor for valor in range(1000)]
    return resultado

print('lista1 toma', timeit(lista1, number=1000), 'segundos')
print('lista2 toma', timeit(lista2, number=1000), 'segundos')

lista1 toma 0.08212313599995014 segundos
lista2 toma 0.033221098000012717 segundos


timeit no admite funciones con argumentos. Esto puede ser demasiado restrictivo en la mayoría de los casos prácticos. La manera más elegante de evadir este problema es con "decoradores", pero no tenemos tiempo de introducirlos. Así que resolvemos este problema "a las malas".

In [42]:
from time import time_ns

In [43]:
def medir_tiempo(func, *args):
    t1 = time_ns()
    func(*args)
    tf = time_ns() - t1
    return tf

In [46]:
def mult(x, veces):
    resultado = x
    for i in range(veces):
        resultado = resultado*x
    return resultado

medir_tiempo(mult, 2, 1)

2000

## Tareas

### Tarea 4.1

Escriba una función que calcule el área de un círculo. Luego calcule las áreas de 100 círculos con radios entre $1$ y $10$ y grafíque el resultado.

### Tarea 4.2

En la clase pasada introdujimos dos funciones que calculan el valor aproximado de $\pi$. 

* Escriba dos funciones que calculen $\pi$ usando cada una de esas aproximaciones respectivamente. Cada función debe tomar el error relativo como input y regresar el valor aproximado de $\pi$ como output. 

* Luego calcule este valor de $\pi$ para diez errores relativos entre $0.1$ y $0.01$. Mida el tiempo que tarda cada uno para cada función y grafique el tiempo de ambas en función del error relativo.

### Tarea 4.3

Defina una función que calcule la serie de Taylor del coseno hasta el $n$-ésimo término. Los inputs son $n$ y el punto $x$ donde se evalúa el coseno. Luego grafique el coseno y las aproximaciones con $n = 2$, $n =6$ en un rango de $x$ que muestre dónde vale la aproximación y dónde se rompe.

### Tarea 4.4

Queremos calcular $x^3$. ¿Es más rápido calcular x\*x\*x o x\*\*3?

El problema es que Python calcula ambas operaciones muy rápido y es imposible decidir cuál es mejor.

Para hacerlo podemos realizar la operación muchas veces y ver cuánto tarda. 

Modifique la función medir_tiempo para que admita un argumento adicional que sea el número de veces que se evalúa la función. Úsela para medir cuál es más rápido entre x\*x\*x o x\*\*3.

### Tarea 4.5

Queremos aproximar $\sin(1)$. Para hacerlo usamos la serie de Taylor hasta el $n$-ésimo término. 

* Defina una función para la aproximación de $\sin(1)$ al $n$-ésimo término.
* Escriba un código que grafique la aproximación en función de $n$. Escoja un rango que permita ver cuándo se obtiene una convergencia aceptable. Este gráfico debe tener barras de error que representen el tamaño del error cometido al hacer la aproximación.